In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("air_quality_data.csv")

In [3]:
dataset.head()

    City        Date  AQI  PM2.5  PM10  NO2  SO2  CO
0  Delhi  2019-01-01  289    176   351   77   26   1
1  Delhi  2019-01-02  268    138   346   92   28   2
2  Delhi  2019-01-03  297    162   373   47   11   1
3  Delhi  2019-01-04  291    162   206   40   21   4
4  Delhi  2019-01-05  259    196   302   66   34   1

In [4]:
dataset.dtypes

City     object
Date     object
AQI       int64
PM2.5     int64
PM10      int64
NO2       int64
SO2       int64
CO        int64
dtype: object

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10960 entries, 0 to 10959
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   City    10960 non-null  object
 1   Date    10960 non-null  object
 2   AQI     10960 non-null  int64
 3   PM2.5   10960 non-null  int64
 4   PM10    10960 non-null  int64
 5   NO2     10960 non-null  int64
 6   SO2     10960 non-null  int64
 7   CO      10960 non-null  int64
dtypes: int64(6), object(2)
memory usage: 685.1+ KB

In [6]:
dataset.isnull().sum()

City     0
Date     0
AQI      0
PM2.5    0
PM10     0
NO2      0
SO2      0
CO       0
dtype: int64

In [7]:
dataset.duplicated().sum()

np.int64(0)

In [8]:
dataset['City'].unique()

array(['Delhi', 'Mumbai', 'Bengaluru', 'Chennai', 'Kolkata'], dtype=object)

In [9]:
dataset = dataset.sort_values(by='Date')

In [10]:
dataset.head()

           City        Date  AQI  PM2.5  PM10  NO2  SO2  CO
0         Delhi  2019-01-01  289    176   351   77   26   1
8768    Kolkata  2019-01-01  240    255   157   33   32   4
2192     Mumbai  2019-01-01  190    129   182   35   38   2
6576    Chennai  2019-01-01  200    243   137   68   41   0
4384  Bengaluru  2019-01-01  156    184   191   33    8   3

In [11]:
dataset['Date'] = pd.to_datetime(dataset['Date'])

In [13]:
dataset.dtypes

City             object
Date     datetime64[ns]
AQI               int64
PM2.5             int64
PM10              int64
NO2               int64
SO2               int64
CO                int64
dtype: object

In [14]:
dataset['City'] = dataset['City'].astype('string')

In [15]:
dataset.dtypes

City     string[python]
Date     datetime64[ns]
AQI               int64
PM2.5             int64
PM10              int64
NO2               int64
SO2               int64
CO                int64
dtype: object

In [16]:
dataset.to_csv("cleaned_air_quality.csv", index=False)